'use strict';

export const LOAD_MY_PROJECTS_SUCCESS = 'LOAD_MY_PROJECTS_SUCCESS';
export const LOAD_MY_PROJECTS_ERROR = 'LOAD_MY_PROJECTS_ERROR';
export const BROWSE_SUCCESS = 'BROWSE_SUCCESS';
export const BROWSE_ERROR = 'BROWSE_ERROR';
