(function() {
	'use strict';

	exports.options = {
		jshint: {
			enforcing: {
				"bitwise": false,
				"camelcase": false,
				"curly": false,
				"enforceall": false,
				"eqeqeq": false,
				"es3": false,
				"es5": false,
				"forin": false,
				"freeze": false,
				"funcscope": false,
				"futurehostile": false,
				"globals": false,
				"immed": false,
				"indent": false,
				"iterator": false,
				"latedef": false,
				"maxcomplexity": false,
				"maxdepth": false,
				"maxerr": false,
				"maxlen": false,
				"maxparams": false,
				"maxstatements": false,
				"newcap": false,
				"noarg": false,
				"nocomma": false,
				"noempty": false,
				"nonbsp": false,
				"nonew": false,
				"notypeof": false,
				"quotmark": false,
				"shadow": false,
				"singleGroups": false,
				"strict": true,
				"undef": true,
				"unused": true,
				"varstmt": false
			},
			relaxing: {
				"asi": true,
				"boss": true,
				"debug": true,
				"elision": true,
				"eqnull": true,
				"esnext": true,
				"evil": true,
				"expr": true,
				"globalstrict": true,
				"lastsemic": true,
				"laxbreak": true,
				"laxcomma": true,
				"loopfunc": true,
				"moz": true,
				"multistr": true,
				"noyield": true,
				"plusplus": true,
				"proto": true,
				"scripturl": true,
				"sub": true,
				"supernew": true,
				"validthis": true,
				"withstmt": true
			},
			environments: {
				"browser": true,
				"browserify": true,
				"couch": true,
				"devel": true,
				"dojo": true,
				"jasmine": true,
				"jquery": true,
				"mocha": true,
				"module": true,
				"mootools": true,
				"node": true,
				"nonstandard": true,
				"phantom": true,
				"prototypejs": true,
				"qunit": true,
				"rhino": true,
				"shelljs": true,
				"typed": true,
				"worker": true,
				"wsh": true,
				"yui": true
			}
		}
	};

})();